
server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: notification-service
  zipkin:
    base-url: 'http://localhost:9411'
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 'localhost:9092'
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.joelmaciel.notificationservice.api.event.OrderPlacedEvent

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
