server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orders?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
    jackson:
      deserialization:
        fail-on-unknown-properties: true
        fail-on-ignored-properties: true
    mvc:
      throw-exception-if-no-handler-found: true
    logging:
      level:
        root: INFO
        org.springframework.web: DEBUG
  logging:
    file:
      path: /app/logs

  zipkin:
    base-url: 'http://localhost:9411'
  sleuth:
    sampler:
      probability: 1.0

  kafka:
    bootstrap-servers: 'localhost:9092'
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.joelmaciel.orderservice.api.event.OrderPlacedEvent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

orderservice:
  queue:
    name: orderQueue

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://eureka:password@localhost:8761/eureka'

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
    health:
      show-details: always


feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s






