server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    register-with-eureka: false
    fetch-registry: false

app:
  eureka:
    username: ${USERNAME_EUREKA}
    password: ${PASSWORD_EUREKA}