server:
  port: 8761

eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    register-with-eureka: false
    fetch-registry: false

app:
  eureka:
    username: eureka
    password: password

spring:
  zipkin:
    base-url: 'http://localhost:9411'
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: prometheus