server:
  port: 8087

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: product-service

  zipkin:
    base-url: 'http://localhost:9411'
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
