
server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3307/inventories?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
    jackson:
      deserialization:
        fail-on-unknown-properties: true
        fail-on-ignored-properties: true
    mvc:
      throw-exception-if-no-handler-found: true
    logging:
      level:
        root: INFO
        org.springframework.web: DEBUG
  logging:
    file:
      path: /app/logs
  zipkin:
    base-url: 'http://localhost:9411'
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka



